/*
    Definition of an Audit Record. This corresponds to a single line in an audit log file,
    which may contain multiple fields. Original implementation uses key/value string pairs
    stored in a HashMap, but could be extended to a more strongly typed structure in the
    future.

    Relevant documentation:
    https://github.com/linux-audit/audit-documentation/blob/main/specs/fields/field-dictionary.csv

    For information on the mapping of netlink messages to auditrs log types, refer to:
    https://codebrowser.dev/linux/include/linux/audit.h.html#147

    need to look into the types presented here:
    https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/6/html/security_guide/sec-understanding_audit_log_files

    and additionally find more modern types
*/

use std::{collections::HashMap, time::SystemTime};

#[derive(Debug, PartialEq)]
pub struct AuditRecord {
    pub record_type: RecordType,
    pub data: String,
}

impl AuditRecord {
    pub fn new(_type: RecordType, data: String) -> Self {
        AuditRecord {
            record_type: _type,
            data,
        }
    }

    pub fn to_log(&self) -> String {
        let field_data = self.data.clone();
        let mut output = String::new();
        if(!self.data.is_empty()) {
            output = format!("type_id={} type={} msg={}", u16::from(self.record_type), self.record_type.as_audit_str(), self.data);
        } else {
        output = format!("type_id={} type={}", u16::from(self.record_type), self.record_type.as_audit_str());
    }
    output
}
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RecordType {
    /* =========================
     * Control (1000–1019)
     * ========================= */
    GetStatus,
    SetStatus,
    List,
    Add,
    Del,
    User,
    Login,
    WatchInsert,
    WatchRemove,
    WatchList,
    SignalInfo,
    AddRule,
    DelRule,
    ListRules,
    Trim,
    MakeEquiv,
    TtyGet,
    TtySet,
    SetFeature,
    GetFeature,

    /* =========================
     * User (1100–1199)
     * ========================= */
    FirstUserMsg,
    UserAcct,
    UserMgmt,
    CredAcq,
    CredDisp,
    UserStart,
    UserEnd,
    UserAvc,
    UserChauthtok,
    UserErr,
    CredRefr,
    UsysConfig,
    UserLogin,
    UserLogout,
    AddUser,
    DelUser,
    AddGroup,
    DelGroup,
    DacCheck,
    ChgrpId,
    Test,
    TrustedApp,
    UserSelinuxErr,
    UserCmd,
    UserTty,
    ChuserId,
    GrpAuth,
    SystemBoot,
    SystemShutdown,
    SystemRunlevel,
    ServiceStart,
    ServiceStop,
    GrpMgmt,
    GrpChauthtok,
    MacCheck,
    AcctLock,
    AcctUnlock,
    UserDevice,
    SoftwareUpdate,
    LastUserMsg,

    /* =========================
     * Daemon (1200–1209)
     * ========================= */
    DaemonStart,
    DaemonEnd,
    DaemonAbort,
    DaemonConfig,
    DaemonReconfig,
    DaemonRotate,
    DaemonResume,
    DaemonAccept,
    DaemonClose,
    DaemonErr,

    /* =========================
     * Kernel (1300–1339)
     * ========================= */
    Syscall,
    Path,
    Ipc,
    Socketcall,
    ConfigChange,
    Sockaddr,
    Cwd,
    Execve,
    IpcSetPerm,
    MqOpen,
    MqSendRecv,
    MqNotify,
    MqGetSetAttr,
    KernelOther,
    FdPair,
    ObjPid,
    Tty,
    Eoe,
    BprmFcaps,
    Capset,
    Mmap,
    NetfilterPkt,
    NetfilterCfg,
    Seccomp,
    Proctitle,
    FeatureChange,
    Replace,
    KernModule,
    Fanotify,
    TimeInjOffset,
    TimeAdjNtpVal,
    Bpf,
    EventListener,
    UringOp,
    Openat2,
    DmCtrl,
    DmEvent,

    /* =========================
     * SELinux (1400–1426)
     * ========================= */
    Avc,
    SelinuxErr,
    AvcPath,
    MacPolicyLoad,
    MacStatus,
    MacConfigChange,
    MacUnlblAllow,
    MacCipsoV4Add,
    MacCipsoV4Del,
    MacMapAdd,
    MacMapDel,
    MacIpsecAddSa,
    MacIpsecDelSa,
    MacIpsecAddSpd,
    MacIpsecDelSpd,
    MacIpsecEvent,
    MacUnlblStcAdd,
    MacUnlblStcDel,
    MacCalipsoAdd,
    MacCalipsoDel,
    IpeAccess,
    IpeConfigChange,
    IpePolicyLoad,
    LandlockAccess,
    LandlockDomain,
    MacTaskContexts,
    MacObjContexts,

    /* =========================
     * AppArmor (1500–1507)
     * ========================= */
    Aa,
    ApparmorAudit,
    ApparmorAllowed,
    ApparmorDenied,
    ApparmorHint,
    ApparmorStatus,
    ApparmorError,
    ApparmorKill,

    /* =========================
     * Kernel Anomaly (1700–1703)
     * ========================= */
    AnomalyPromiscuous,
    AnomalyAbend,
    AnomalyLink,
    AnomalyCreat,

    /* =========================
     * Integrity (1800–1808)
     * ========================= */
    IntegrityData,
    IntegrityMetadata,
    IntegrityStatus,
    IntegrityHash,
    IntegrityPcr,
    IntegrityRule,
    IntegrityEvmXattr,
    IntegrityPolicyRule,
    IntegrityUserspace,

    /* =========================
     * Legacy (2000)
     * ========================= */
    Kernel,

    /* =========================
     * User Anomaly (2100–2121)
     * ========================= */
    AnomalyLoginFailures,
    AnomalyLoginTime,
    AnomalyLoginSessions,
    AnomalyLoginAcct,
    AnomalyLoginLocation,
    AnomalyMaxDac,
    AnomalyMaxMac,
    AnomalyAmtuFail,
    AnomalyRbacFail,
    AnomalyRbacIntegrityFail,
    AnomalyCryptoFail,
    AnomalyAccessFs,
    AnomalyExec,
    AnomalyMkExec,
    AnomalyAddAcct,
    AnomalyDelAcct,
    AnomalyModAcct,
    AnomalyRootTrans,
    AnomalyLoginService,
    AnomalyLoginRoot,
    AnomalyOriginFailures,
    AnomalySession,

    /* =========================
     * Anomaly Response (2200–2215)
     * ========================= */
    RespAnomaly,
    RespAlert,
    RespKillProc,
    RespTermAccess,
    RespAcctRemote,
    RespAcctLockTimed,
    RespAcctUnlockTimed,
    RespAcctLock,
    RespTermLock,
    RespSebool,
    RespExec,
    RespSingle,
    RespHalt,
    RespOriginBlock,
    RespOriginBlockTimed,
    RespOriginUnblockTimed,

    /* =========================
     * User LSPP (2300–2313)
     * ========================= */
    UserRoleChange,
    RoleAssign,
    RoleRemove,
    LabelOverride,
    LabelLevelChange,
    UserLabeledExport,
    UserUnlabeledExport,
    DevAlloc,
    DevDealloc,
    FsRelabel,
    UserMacPolicyLoad,
    RoleModify,
    UserMacConfigChange,
    UserMacStatus,

    /* =========================
     * User Crypto (2400–2409)
     * ========================= */
    CryptoTestUser,
    CryptoParamChangeUser,
    CryptoLogin,
    CryptoLogout,
    CryptoKeyUser,
    CryptoFailureUser,
    CryptoReplayUser,
    CryptoSession,
    CryptoIkeSa,
    CryptoIpsecSa,

    /* =========================
     * Virtualization (2500–2507)
     * ========================= */
    VirtControl,
    VirtResource,
    VirtMachineId,
    VirtIntegrityCheck,
    VirtCreate,
    VirtDestroy,
    VirtMigrateIn,
    VirtMigrateOut,

    /* =========================
     * Fallback
     * ========================= */
    Unknown(u16),
}

impl RecordType {
    pub fn as_audit_str(&self) -> &'static str {
        match self {
            // Control
            Self::GetStatus => "GET_STATUS",
            Self::SetStatus => "SET_STATUS",
            Self::List => "LIST",
            Self::Add => "ADD",
            Self::Del => "DEL",
            Self::User => "USER",
            Self::Login => "LOGIN",
            Self::WatchInsert => "WATCH_INSERT",
            Self::WatchRemove => "WATCH_REMOVE",
            Self::WatchList => "WATCH_LIST",
            Self::SignalInfo => "SIGNAL_INFO",
            Self::AddRule => "ADD_RULE",
            Self::DelRule => "DEL_RULE",
            Self::ListRules => "LIST_RULES",
            Self::Trim => "TRIM",
            Self::MakeEquiv => "MAKE_EQUIV",
            Self::TtyGet => "TTY_GET",
            Self::TtySet => "TTY_SET",
            Self::SetFeature => "SET_FEATURE",
            Self::GetFeature => "GET_FEATURE",

            // User
            Self::FirstUserMsg => "USER_FIRST_MSG",
            Self::UserAcct => "USER_ACCT",
            Self::UserMgmt => "USER_MGMT",
            Self::CredAcq => "CRED_ACQ",
            Self::CredDisp => "CRED_DISP",
            Self::UserStart => "USER_START",
            Self::UserEnd => "USER_END",
            Self::UserAvc => "USER_AVC",
            Self::UserChauthtok => "USER_CHAUTHTOK",
            Self::UserErr => "USER_ERR",
            Self::CredRefr => "CRED_REFR",
            Self::UsysConfig => "USYS_CONFIG",
            Self::UserLogin => "USER_LOGIN",
            Self::UserLogout => "USER_LOGOUT",
            Self::AddUser => "ADD_USER",
            Self::DelUser => "DEL_USER",
            Self::AddGroup => "ADD_GROUP",
            Self::DelGroup => "DEL_GROUP",
            Self::DacCheck => "DAC_CHECK",
            Self::ChgrpId => "CHGRP_ID",
            Self::Test => "TEST",
            Self::TrustedApp => "TRUSTED_APP",
            Self::UserSelinuxErr => "USER_SELINUX_ERR",
            Self::UserCmd => "USER_CMD",
            Self::UserTty => "USER_TTY",
            Self::ChuserId => "CHUSER_ID",
            Self::GrpAuth => "GRP_AUTH",
            Self::SystemBoot => "SYSTEM_BOOT",
            Self::SystemShutdown => "SYSTEM_SHUTDOWN",
            Self::SystemRunlevel => "SYSTEM_RUNLEVEL",
            Self::ServiceStart => "SERVICE_START",
            Self::ServiceStop => "SERVICE_STOP",
            Self::GrpMgmt => "GRP_MGMT",
            Self::GrpChauthtok => "GRP_CHAUTHTOK",
            Self::MacCheck => "MAC_CHECK",
            Self::AcctLock => "ACCT_LOCK",
            Self::AcctUnlock => "ACCT_UNLOCK",
            Self::UserDevice => "USER_DEVICE",
            Self::SoftwareUpdate => "SOFTWARE_UPDATE",
            Self::LastUserMsg => "USER_LAST_MSG",

            // Daemon
            Self::DaemonStart => "DAEMON_START",
            Self::DaemonEnd => "DAEMON_END",
            Self::DaemonAbort => "DAEMON_ABORT",
            Self::DaemonConfig => "DAEMON_CONFIG",
            Self::DaemonReconfig => "DAEMON_RECONFIG",
            Self::DaemonRotate => "DAEMON_ROTATE",
            Self::DaemonResume => "DAEMON_RESUME",
            Self::DaemonAccept => "DAEMON_ACCEPT",
            Self::DaemonClose => "DAEMON_CLOSE",
            Self::DaemonErr => "DAEMON_ERR",

            // Kernel
            Self::Syscall => "SYSCALL",
            Self::Path => "PATH",
            Self::Ipc => "IPC",
            Self::Socketcall => "SOCKETCALL",
            Self::ConfigChange => "CONFIG_CHANGE",
            Self::Sockaddr => "SOCKADDR",
            Self::Cwd => "CWD",
            Self::Execve => "EXECVE",
            Self::IpcSetPerm => "IPC_SET_PERM",
            Self::MqOpen => "MQ_OPEN",
            Self::MqSendRecv => "MQ_SEND_RECV",
            Self::MqNotify => "MQ_NOTIFY",
            Self::MqGetSetAttr => "MQ_GETSETATTR",
            Self::KernelOther => "KERNEL_OTHER",
            Self::FdPair => "FD_PAIR",
            Self::ObjPid => "OBJ_PID",
            Self::Tty => "TTY",
            Self::Eoe => "EOE",
            Self::BprmFcaps => "BPRM_FCAPS",
            Self::Capset => "CAPSET",
            Self::Mmap => "MMAP",
            Self::NetfilterPkt => "NETFILTER_PKT",
            Self::NetfilterCfg => "NETFILTER_CFG",
            Self::Seccomp => "SECCOMP",
            Self::Proctitle => "PROCTITLE",
            Self::FeatureChange => "FEATURE_CHANGE",
            Self::Replace => "REPLACE",
            Self::KernModule => "KERN_MODULE",
            Self::Fanotify => "FANOTIFY",
            Self::TimeInjOffset => "TIME_INJ_OFFSET",
            Self::TimeAdjNtpVal => "TIME_ADJ_NTP_VAL",
            Self::Bpf => "BPF",
            Self::EventListener => "EVENT_LISTENER",
            Self::UringOp => "URINGOP",
            Self::Openat2 => "OPENAT2",
            Self::DmCtrl => "DM_CTRL",
            Self::DmEvent => "DM_EVENT",

            // SELinux
            Self::Avc => "AVC",
            Self::SelinuxErr => "SELINUX_ERR",
            Self::AvcPath => "AVC_PATH",
            Self::MacPolicyLoad => "MAC_POLICY_LOAD",
            Self::MacStatus => "MAC_STATUS",
            Self::MacConfigChange => "MAC_CONFIG_CHANGE",
            Self::MacUnlblAllow => "MAC_UNLBL_ALLOW",
            Self::MacCipsoV4Add => "MAC_CIPSO_V4_ADD",
            Self::MacCipsoV4Del => "MAC_CIPSO_V4_DEL",
            Self::MacMapAdd => "MAC_MAP_ADD",
            Self::MacMapDel => "MAC_MAP_DEL",
            Self::MacIpsecAddSa => "MAC_IPSEC_ADDSA",
            Self::MacIpsecDelSa => "MAC_IPSEC_DELSA",
            Self::MacIpsecAddSpd => "MAC_IPSEC_ADDSPD",
            Self::MacIpsecDelSpd => "MAC_IPSEC_DELSPD",
            Self::MacIpsecEvent => "MAC_IPSEC_EVENT",
            Self::MacUnlblStcAdd => "MAC_UNLBL_STC_ADD",
            Self::MacUnlblStcDel => "MAC_UNLBL_STC_DEL",
            Self::MacCalipsoAdd => "MAC_CALIPSO_ADD",
            Self::MacCalipsoDel => "MAC_CALIPSO_DEL",
            Self::IpeAccess => "IPE_ACCESS",
            Self::IpeConfigChange => "IPE_CONFIG_CHANGE",
            Self::IpePolicyLoad => "IPE_POLICY_LOAD",
            Self::LandlockAccess => "LANDLOCK_ACCESS",
            Self::LandlockDomain => "LANDLOCK_DOMAIN",
            Self::MacTaskContexts => "MAC_TASK_CONTEXTS",
            Self::MacObjContexts => "MAC_OBJ_CONTEXTS",

            // AppArmor
            Self::Aa => "AA",
            Self::ApparmorAudit => "APPARMOR_AUDIT",
            Self::ApparmorAllowed => "APPARMOR_ALLOWED",
            Self::ApparmorDenied => "APPARMOR_DENIED",
            Self::ApparmorHint => "APPARMOR_HINT",
            Self::ApparmorStatus => "APPARMOR_STATUS",
            Self::ApparmorError => "APPARMOR_ERROR",
            Self::ApparmorKill => "APPARMOR_KILL",

            // Kernel Anomaly
            Self::AnomalyPromiscuous => "ANOM_PROMISCUOUS",
            Self::AnomalyAbend => "ANOM_ABEND",
            Self::AnomalyLink => "ANOM_LINK",
            Self::AnomalyCreat => "ANOM_CREAT",

            // Integrity
            Self::IntegrityData => "INTEGRITY_DATA",
            Self::IntegrityMetadata => "INTEGRITY_METADATA",
            Self::IntegrityStatus => "INTEGRITY_STATUS",
            Self::IntegrityHash => "INTEGRITY_HASH",
            Self::IntegrityPcr => "INTEGRITY_PCR",
            Self::IntegrityRule => "INTEGRITY_RULE",
            Self::IntegrityEvmXattr => "INTEGRITY_EVM_XATTR",
            Self::IntegrityPolicyRule => "INTEGRITY_POLICY_RULE",
            Self::IntegrityUserspace => "INTEGRITY_USERSPACE",

            // Legacy
            Self::Kernel => "KERNEL",

            // User Anomaly
            Self::AnomalyLoginFailures => "ANOM_LOGIN_FAILURES",
            Self::AnomalyLoginTime => "ANOM_LOGIN_TIME",
            Self::AnomalyLoginSessions => "ANOM_LOGIN_SESSIONS",
            Self::AnomalyLoginAcct => "ANOM_LOGIN_ACCT",
            Self::AnomalyLoginLocation => "ANOM_LOGIN_LOCATION",
            Self::AnomalyMaxDac => "ANOM_MAX_DAC",
            Self::AnomalyMaxMac => "ANOM_MAX_MAC",
            Self::AnomalyAmtuFail => "ANOM_AMTU_FAIL",
            Self::AnomalyRbacFail => "ANOM_RBAC_FAIL",
            Self::AnomalyRbacIntegrityFail => "ANOM_RBAC_INTEGRITY_FAIL",
            Self::AnomalyCryptoFail => "ANOM_CRYPTO_FAIL",
            Self::AnomalyAccessFs => "ANOM_ACCESS_FS",
            Self::AnomalyExec => "ANOM_EXEC",
            Self::AnomalyMkExec => "ANOM_MK_EXEC",
            Self::AnomalyAddAcct => "ANOM_ADD_ACCT",
            Self::AnomalyDelAcct => "ANOM_DEL_ACCT",
            Self::AnomalyModAcct => "ANOM_MOD_ACCT",
            Self::AnomalyRootTrans => "ANOM_ROOT_TRANS",
            Self::AnomalyLoginService => "ANOM_LOGIN_SERVICE",
            Self::AnomalyLoginRoot => "ANOM_LOGIN_ROOT",
            Self::AnomalyOriginFailures => "ANOM_ORIGIN_FAILURES",
            Self::AnomalySession => "ANOM_SESSION",

            // Anomaly Response
            Self::RespAnomaly => "RESP_ANOMALY",
            Self::RespAlert => "RESP_ALERT",
            Self::RespKillProc => "RESP_KILL_PROC",
            Self::RespTermAccess => "RESP_TERM_ACCESS",
            Self::RespAcctRemote => "RESP_ACCT_REMOTE",
            Self::RespAcctLockTimed => "RESP_ACCT_LOCK_TIMED",
            Self::RespAcctUnlockTimed => "RESP_ACCT_UNLOCK_TIMED",
            Self::RespAcctLock => "RESP_ACCT_LOCK",
            Self::RespTermLock => "RESP_TERM_LOCK",
            Self::RespSebool => "RESP_SEBOOL",
            Self::RespExec => "RESP_EXEC",
            Self::RespSingle => "RESP_SINGLE",
            Self::RespHalt => "RESP_HALT",
            Self::RespOriginBlock => "RESP_ORIGIN_BLOCK",
            Self::RespOriginBlockTimed => "RESP_ORIGIN_BLOCK_TIMED",
            Self::RespOriginUnblockTimed => "RESP_ORIGIN_UNBLOCK_TIMED",

            // User LSPP
            Self::UserRoleChange => "USER_ROLE_CHANGE",
            Self::RoleAssign => "ROLE_ASSIGN",
            Self::RoleRemove => "ROLE_REMOVE",
            Self::LabelOverride => "LABEL_OVERRIDE",
            Self::LabelLevelChange => "LABEL_LEVEL_CHANGE",
            Self::UserLabeledExport => "USER_LABELED_EXPORT",
            Self::UserUnlabeledExport => "USER_UNLABELED_EXPORT",
            Self::DevAlloc => "DEV_ALLOC",
            Self::DevDealloc => "DEV_DEALLOC",
            Self::FsRelabel => "FS_RELABEL",
            Self::UserMacPolicyLoad => "USER_MAC_POLICY_LOAD",
            Self::RoleModify => "ROLE_MODIFY",
            Self::UserMacConfigChange => "USER_MAC_CONFIG_CHANGE",
            Self::UserMacStatus => "USER_MAC_STATUS",

            // User Crypto
            Self::CryptoTestUser => "CRYPTO_TEST_USER",
            Self::CryptoParamChangeUser => "CRYPTO_PARAM_CHANGE_USER",
            Self::CryptoLogin => "CRYPTO_LOGIN",
            Self::CryptoLogout => "CRYPTO_LOGOUT",
            Self::CryptoKeyUser => "CRYPTO_KEY_USER",
            Self::CryptoFailureUser => "CRYPTO_FAILURE_USER",
            Self::CryptoReplayUser => "CRYPTO_REPLAY_USER",
            Self::CryptoSession => "CRYPTO_SESSION",
            Self::CryptoIkeSa => "CRYPTO_IKE_SA",
            Self::CryptoIpsecSa => "CRYPTO_IPSEC_SA",

            // Virtualization
            Self::VirtControl => "VIRT_CONTROL",
            Self::VirtResource => "VIRT_RESOURCE",
            Self::VirtMachineId => "VIRT_MACHINE_ID",
            Self::VirtIntegrityCheck => "VIRT_INTEGRITY_CHECK",
            Self::VirtCreate => "VIRT_CREATE",
            Self::VirtDestroy => "VIRT_DESTROY",
            Self::VirtMigrateIn => "VIRT_MIGRATE_IN",
            Self::VirtMigrateOut => "VIRT_MIGRATE_OUT",

            // Fallback
            Self::Unknown(_) => "UNKNOWN",
        }
    }
}

impl From<u16> for RecordType {
    fn from(value: u16) -> Self {
        use RecordType::*;

        match value {
            // Control
            1000 => GetStatus,
            1001 => SetStatus,
            1002 => List,
            1003 => Add,
            1004 => Del,
            1005 => User,
            1006 => Login,
            1007 => WatchInsert,
            1008 => WatchRemove,
            1009 => WatchList,
            1010 => SignalInfo,
            1011 => AddRule,
            1012 => DelRule,
            1013 => ListRules,
            1014 => Trim,
            1015 => MakeEquiv,
            1016 => TtyGet,
            1017 => TtySet,
            1018 => SetFeature,
            1019 => GetFeature,

            // User
            1100 => FirstUserMsg,
            1101 => UserAcct,
            1102 => UserMgmt,
            1103 => CredAcq,
            1104 => CredDisp,
            1105 => UserStart,
            1106 => UserEnd,
            1107 => UserAvc,
            1108 => UserChauthtok,
            1109 => UserErr,
            1110 => CredRefr,
            1111 => UsysConfig,
            1112 => UserLogin,
            1113 => UserLogout,
            1114 => AddUser,
            1115 => DelUser,
            1116 => AddGroup,
            1117 => DelGroup,
            1118 => DacCheck,
            1119 => ChgrpId,
            1120 => Test,
            1121 => TrustedApp,
            1122 => UserSelinuxErr,
            1123 => UserCmd,
            1124 => UserTty,
            1125 => ChuserId,
            1126 => GrpAuth,
            1127 => SystemBoot,
            1128 => SystemShutdown,
            1129 => SystemRunlevel,
            1130 => ServiceStart,
            1131 => ServiceStop,
            1132 => GrpMgmt,
            1133 => GrpChauthtok,
            1134 => MacCheck,
            1135 => AcctLock,
            1136 => AcctUnlock,
            1137 => UserDevice,
            1138 => SoftwareUpdate,
            1199 => LastUserMsg,

            // Daemon
            1200 => DaemonStart,
            1201 => DaemonEnd,
            1202 => DaemonAbort,
            1203 => DaemonConfig,
            1204 => DaemonReconfig,
            1205 => DaemonRotate,
            1206 => DaemonResume,
            1207 => DaemonAccept,
            1208 => DaemonClose,
            1209 => DaemonErr,

            // Kernel
            1300 => Syscall,
            1302 => Path,
            1303 => Ipc,
            1304 => Socketcall,
            1305 => ConfigChange,
            1306 => Sockaddr,
            1307 => Cwd,
            1309 => Execve,
            1311 => IpcSetPerm,
            1312 => MqOpen,
            1313 => MqSendRecv,
            1314 => MqNotify,
            1315 => MqGetSetAttr,
            1316 => KernelOther,
            1317 => FdPair,
            1318 => ObjPid,
            1319 => Tty,
            1320 => Eoe,
            1321 => BprmFcaps,
            1322 => Capset,
            1323 => Mmap,
            1324 => NetfilterPkt,
            1325 => NetfilterCfg,
            1326 => Seccomp,
            1327 => Proctitle,
            1328 => FeatureChange,
            1329 => Replace,
            1330 => KernModule,
            1331 => Fanotify,
            1332 => TimeInjOffset,
            1333 => TimeAdjNtpVal,
            1334 => Bpf,
            1335 => EventListener,
            1336 => UringOp,
            1337 => Openat2,
            1338 => DmCtrl,
            1339 => DmEvent,

            // SELinux
            1400 => Avc,
            1401 => SelinuxErr,
            1402 => AvcPath,
            1403 => MacPolicyLoad,
            1404 => MacStatus,
            1405 => MacConfigChange,
            1406 => MacUnlblAllow,
            1407 => MacCipsoV4Add,
            1408 => MacCipsoV4Del,
            1409 => MacMapAdd,
            1410 => MacMapDel,
            1411 => MacIpsecAddSa,
            1412 => MacIpsecDelSa,
            1413 => MacIpsecAddSpd,
            1414 => MacIpsecDelSpd,
            1415 => MacIpsecEvent,
            1416 => MacUnlblStcAdd,
            1417 => MacUnlblStcDel,
            1418 => MacCalipsoAdd,
            1419 => MacCalipsoDel,
            1420 => IpeAccess,
            1421 => IpeConfigChange,
            1422 => IpePolicyLoad,
            1423 => LandlockAccess,
            1424 => LandlockDomain,
            1425 => MacTaskContexts,
            1426 => MacObjContexts,

            // AppArmor
            1500 => Aa,
            1501 => ApparmorAudit,
            1502 => ApparmorAllowed,
            1503 => ApparmorDenied,
            1504 => ApparmorHint,
            1505 => ApparmorStatus,
            1506 => ApparmorError,
            1507 => ApparmorKill,

            // Kernel Anomaly
            1700 => AnomalyPromiscuous,
            1701 => AnomalyAbend,
            1702 => AnomalyLink,
            1703 => AnomalyCreat,

            // Integrity
            1800 => IntegrityData,
            1801 => IntegrityMetadata,
            1802 => IntegrityStatus,
            1803 => IntegrityHash,
            1804 => IntegrityPcr,
            1805 => IntegrityRule,
            1806 => IntegrityEvmXattr,
            1807 => IntegrityPolicyRule,
            1808 => IntegrityUserspace,

            // Legacy
            2000 => Kernel,

            // User Anomaly
            2100 => AnomalyLoginFailures,
            2101 => AnomalyLoginTime,
            2102 => AnomalyLoginSessions,
            2103 => AnomalyLoginAcct,
            2104 => AnomalyLoginLocation,
            2105 => AnomalyMaxDac,
            2106 => AnomalyMaxMac,
            2107 => AnomalyAmtuFail,
            2108 => AnomalyRbacFail,
            2109 => AnomalyRbacIntegrityFail,
            2110 => AnomalyCryptoFail,
            2111 => AnomalyAccessFs,
            2112 => AnomalyExec,
            2113 => AnomalyMkExec,
            2114 => AnomalyAddAcct,
            2115 => AnomalyDelAcct,
            2116 => AnomalyModAcct,
            2117 => AnomalyRootTrans,
            2118 => AnomalyLoginService,
            2119 => AnomalyLoginRoot,
            2120 => AnomalyOriginFailures,
            2121 => AnomalySession,

            // Anomaly Response
            2200 => RespAnomaly,
            2201 => RespAlert,
            2202 => RespKillProc,
            2203 => RespTermAccess,
            2204 => RespAcctRemote,
            2205 => RespAcctLockTimed,
            2206 => RespAcctUnlockTimed,
            2207 => RespAcctLock,
            2208 => RespTermLock,
            2209 => RespSebool,
            2210 => RespExec,
            2211 => RespSingle,
            2212 => RespHalt,
            2213 => RespOriginBlock,
            2214 => RespOriginBlockTimed,
            2215 => RespOriginUnblockTimed,

            // User LSPP
            2300 => UserRoleChange,
            2301 => RoleAssign,
            2302 => RoleRemove,
            2303 => LabelOverride,
            2304 => LabelLevelChange,
            2305 => UserLabeledExport,
            2306 => UserUnlabeledExport,
            2307 => DevAlloc,
            2308 => DevDealloc,
            2309 => FsRelabel,
            2310 => UserMacPolicyLoad,
            2311 => RoleModify,
            2312 => UserMacConfigChange,
            2313 => UserMacStatus,

            // User Crypto
            2400 => CryptoTestUser,
            2401 => CryptoParamChangeUser,
            2402 => CryptoLogin,
            2403 => CryptoLogout,
            2404 => CryptoKeyUser,
            2405 => CryptoFailureUser,
            2406 => CryptoReplayUser,
            2407 => CryptoSession,
            2408 => CryptoIkeSa,
            2409 => CryptoIpsecSa,

            // Virtualization
            2500 => VirtControl,
            2501 => VirtResource,
            2502 => VirtMachineId,
            2503 => VirtIntegrityCheck,
            2504 => VirtCreate,
            2505 => VirtDestroy,
            2506 => VirtMigrateIn,
            2507 => VirtMigrateOut,

            other => Unknown(other),
        }
    }
}

impl From<RecordType> for u16 {
    fn from(value: RecordType) -> Self {
        use RecordType::*;

        match value {
            GetStatus => 1000,
            SetStatus => 1001,
            List => 1002,
            Add => 1003,
            Del => 1004,
            User => 1005,
            Login => 1006,
            WatchInsert => 1007,
            WatchRemove => 1008,
            WatchList => 1009,
            SignalInfo => 1010,
            AddRule => 1011,
            DelRule => 1012,
            ListRules => 1013,
            Trim => 1014,
            MakeEquiv => 1015,
            TtyGet => 1016,
            TtySet => 1017,
            SetFeature => 1018,
            GetFeature => 1019,

            FirstUserMsg => 1100,
            UserAcct => 1101,
            UserMgmt => 1102,
            CredAcq => 1103,
            CredDisp => 1104,
            UserStart => 1105,
            UserEnd => 1106,
            UserAvc => 1107,
            UserChauthtok => 1108,
            UserErr => 1109,
            CredRefr => 1110,
            UsysConfig => 1111,
            UserLogin => 1112,
            UserLogout => 1113,
            AddUser => 1114,
            DelUser => 1115,
            AddGroup => 1116,
            DelGroup => 1117,
            DacCheck => 1118,
            ChgrpId => 1119,
            Test => 1120,
            TrustedApp => 1121,
            UserSelinuxErr => 1122,
            UserCmd => 1123,
            UserTty => 1124,
            ChuserId => 1125,
            GrpAuth => 1126,
            SystemBoot => 1127,
            SystemShutdown => 1128,
            SystemRunlevel => 1129,
            ServiceStart => 1130,
            ServiceStop => 1131,
            GrpMgmt => 1132,
            GrpChauthtok => 1133,
            MacCheck => 1134,
            AcctLock => 1135,
            AcctUnlock => 1136,
            UserDevice => 1137,
            SoftwareUpdate => 1138,
            LastUserMsg => 1199,

            DaemonStart => 1200,
            DaemonEnd => 1201,
            DaemonAbort => 1202,
            DaemonConfig => 1203,
            DaemonReconfig => 1204,
            DaemonRotate => 1205,
            DaemonResume => 1206,
            DaemonAccept => 1207,
            DaemonClose => 1208,
            DaemonErr => 1209,

            Syscall => 1300,
            Path => 1302,
            Ipc => 1303,
            Socketcall => 1304,
            ConfigChange => 1305,
            Sockaddr => 1306,
            Cwd => 1307,
            Execve => 1309,
            IpcSetPerm => 1311,
            MqOpen => 1312,
            MqSendRecv => 1313,
            MqNotify => 1314,
            MqGetSetAttr => 1315,
            KernelOther => 1316,
            FdPair => 1317,
            ObjPid => 1318,
            Tty => 1319,
            Eoe => 1320,
            BprmFcaps => 1321,
            Capset => 1322,
            Mmap => 1323,
            NetfilterPkt => 1324,
            NetfilterCfg => 1325,
            Seccomp => 1326,
            Proctitle => 1327,
            FeatureChange => 1328,
            Replace => 1329,
            KernModule => 1330,
            Fanotify => 1331,
            TimeInjOffset => 1332,
            TimeAdjNtpVal => 1333,
            Bpf => 1334,
            EventListener => 1335,
            UringOp => 1336,
            Openat2 => 1337,
            DmCtrl => 1338,
            DmEvent => 1339,

            Avc => 1400,
            SelinuxErr => 1401,
            AvcPath => 1402,
            MacPolicyLoad => 1403,
            MacStatus => 1404,
            MacConfigChange => 1405,
            MacUnlblAllow => 1406,
            MacCipsoV4Add => 1407,
            MacCipsoV4Del => 1408,
            MacMapAdd => 1409,
            MacMapDel => 1410,
            MacIpsecAddSa => 1411,
            MacIpsecDelSa => 1412,
            MacIpsecAddSpd => 1413,
            MacIpsecDelSpd => 1414,
            MacIpsecEvent => 1415,
            MacUnlblStcAdd => 1416,
            MacUnlblStcDel => 1417,
            MacCalipsoAdd => 1418,
            MacCalipsoDel => 1419,
            IpeAccess => 1420,
            IpeConfigChange => 1421,
            IpePolicyLoad => 1422,
            LandlockAccess => 1423,
            LandlockDomain => 1424,
            MacTaskContexts => 1425,
            MacObjContexts => 1426,

            Aa => 1500,
            ApparmorAudit => 1501,
            ApparmorAllowed => 1502,
            ApparmorDenied => 1503,
            ApparmorHint => 1504,
            ApparmorStatus => 1505,
            ApparmorError => 1506,
            ApparmorKill => 1507,

            AnomalyPromiscuous => 1700,
            AnomalyAbend => 1701,
            AnomalyLink => 1702,
            AnomalyCreat => 1703,

            IntegrityData => 1800,
            IntegrityMetadata => 1801,
            IntegrityStatus => 1802,
            IntegrityHash => 1803,
            IntegrityPcr => 1804,
            IntegrityRule => 1805,
            IntegrityEvmXattr => 1806,
            IntegrityPolicyRule => 1807,
            IntegrityUserspace => 1808,

            Kernel => 2000,

            AnomalyLoginFailures => 2100,
            AnomalyLoginTime => 2101,
            AnomalyLoginSessions => 2102,
            AnomalyLoginAcct => 2103,
            AnomalyLoginLocation => 2104,
            AnomalyMaxDac => 2105,
            AnomalyMaxMac => 2106,
            AnomalyAmtuFail => 2107,
            AnomalyRbacFail => 2108,
            AnomalyRbacIntegrityFail => 2109,
            AnomalyCryptoFail => 2110,
            AnomalyAccessFs => 2111,
            AnomalyExec => 2112,
            AnomalyMkExec => 2113,
            AnomalyAddAcct => 2114,
            AnomalyDelAcct => 2115,
            AnomalyModAcct => 2116,
            AnomalyRootTrans => 2117,
            AnomalyLoginService => 2118,
            AnomalyLoginRoot => 2119,
            AnomalyOriginFailures => 2120,
            AnomalySession => 2121,

            RespAnomaly => 2200,
            RespAlert => 2201,
            RespKillProc => 2202,
            RespTermAccess => 2203,
            RespAcctRemote => 2204,
            RespAcctLockTimed => 2205,
            RespAcctUnlockTimed => 2206,
            RespAcctLock => 2207,
            RespTermLock => 2208,
            RespSebool => 2209,
            RespExec => 2210,
            RespSingle => 2211,
            RespHalt => 2212,
            RespOriginBlock => 2213,
            RespOriginBlockTimed => 2214,
            RespOriginUnblockTimed => 2215,

            UserRoleChange => 2300,
            RoleAssign => 2301,
            RoleRemove => 2302,
            LabelOverride => 2303,
            LabelLevelChange => 2304,
            UserLabeledExport => 2305,
            UserUnlabeledExport => 2306,
            DevAlloc => 2307,
            DevDealloc => 2308,
            FsRelabel => 2309,
            UserMacPolicyLoad => 2310,
            RoleModify => 2311,
            UserMacConfigChange => 2312,
            UserMacStatus => 2313,

            CryptoTestUser => 2400,
            CryptoParamChangeUser => 2401,
            CryptoLogin => 2402,
            CryptoLogout => 2403,
            CryptoKeyUser => 2404,
            CryptoFailureUser => 2405,
            CryptoReplayUser => 2406,
            CryptoSession => 2407,
            CryptoIkeSa => 2408,
            CryptoIpsecSa => 2409,

            VirtControl => 2500,
            VirtResource => 2501,
            VirtMachineId => 2502,
            VirtIntegrityCheck => 2503,
            VirtCreate => 2504,
            VirtDestroy => 2505,
            VirtMigrateIn => 2506,
            VirtMigrateOut => 2507,

            Unknown(v) => v,
        }
    }
}

#[cfg(test)]
pub mod test {
    use super::*;

    #[test]
    fn test_record_to_log() {
        let record_type = RecordType::from(1300); // Syscall
        let record = AuditRecord::new(record_type, "example data".to_string());
        assert_eq!(record.record_type.as_audit_str(), "SYSCALL");
        assert_eq!(record.to_log(), "type=SYSCALL msg=example data");

        // Round-trip u16 conversion
        let num: u16 = record_type.into();
        assert_eq!(num, 1300);
        assert_eq!(RecordType::from(num), record_type);
    }
}
